### ISSUE TITLE
Install with Board manager 1.6.6 return CRC error

### ISSUE THREAD

**Issue by pierrotm777** [Quirkbot/QuirkbotArduinoHardware#1]
Bad CRC is returned

**Comment by paulobarcelos** [comment]
Related to issue #2

I've just made a new update to the hardware specification, and changed the way it get's packaged.
Hopefully this was solved now. At least it working here for me on a mac.
Could you make a test and report your results?

**Comment by pierrotm777** [comment]
It's ok for me . Thanks :-)
