### ISSUE TITLE
Could not find boards.txt in .arduino15/packages/quirkbot/hardware/avr/0.0.14

### ISSUE THREAD

**Issue by xranby** [Quirkbot/QuirkbotArduinoHardware#2]
There is an issue with the internal format of the archive stored at
http://code.quirkbot.com/downloads/quirkbot-avr.tar.bz2

when this archive is downloaded using the "Additional Boards Managers URLs:" in Arduino 1.6.5
https://raw.githubusercontent.com/Quirkbot/QuirkbotArduinoHardware/master/package_quirkbot.com_index.json
the file gets unpacked into
.arduino15/packages/quirkbot/hardware/avr/0.0.14/avr
however arduino expects the files to get unpacked into
.arduino15/packages/quirkbot/hardware/avr/0.0.14

Arduino will report an error to the user such as:
"Kunde inte hitta boards.txt i /home/xranby/.arduino15/packages/quirkbot/hardware/avr/0.0.14, Är det pre-1.5?"

By moving all files from 
.arduino15/packages/quirkbot/hardware/avr/0.0.14/avr/*
to
.arduino15/packages/quirkbot/hardware/avr/0.0.14/
workaround the issue.

Issue description with workaround in Swedish below: 

Efter att man har startat Arduino går man till
Fil menyn -> Inställningar
Där finns ett fält "Additional Boards Managers URLs:" i den tomma rutan fyller man i
https://raw.githubusercontent.com/Quirkbot/QuirkbotArduinoHardware/master/package_quirkbot.com_index.json
tryck sedan på OK

Sedan väljer man Verktyg -> Kort: -> Boards Manager...
I BoardsManager skriver man in "Quirk" i sökrutan
Då visas Quirkbot AVR Boards by Quirkbot i rutan nedan
Markera sökresultatet "Quirkbot AVR Boards by Quirkbot"
en knapp "Install" visas, tryck på Install knappen
Tryck sedan på Stäng knappen

Arduino kommer nu visa med röd text i Arduinos svarta ruta:
Kunde inte hitta boards.txt i /home/xranby/.arduino15/packages/quirkbot/hardware/avr/0.0.14, Är det pre-1.5?
Detta är en bugg och åtgärdas manuellt genom att öppna en filhanterare fönster och gå till katalogen som nämns i felmeddelandet
I katalogen
.arduino15/packages/quirkbot/hardware/avr/0.0.14
finner man en underkatalog med namn
avr
markera och kopiera alla filer från denna underkatalog gå sedan till 0.0.14 katalogen och klistra in
Välj Arduino fönstret igen och gå sedan igen in i BoardsManager och välj stäng en gång till. arduino har nu hittat quirkbot tillägget
det kommer fortfarande stå "/home/xranby/.arduino15/packages/quirkbot/hardware/avr/0.0.14, Är det pre-1.5?" i loggen men det är bara det gamla felmeddelandet.

**Comment by paulobarcelos** [comment]
Thanks for all the effort in digging into this @xranby!

I've just made a new update to the hardware specification, and changed the way it get's packaged.

Hopefully this was solved now. At least it works for me all the time.

Could you make a test and report your results?
